### ISSUE TITLE
Matrix-Signal usernames contain unicode

### ISSUE THREAD

**Issue by DerBeutlin** [matrix-hacks/matrix-puppet-signal#18]
I did not succeeded in setting up this bridge.
Whenever I receive a signal message the signal bots sends me the following error
```[M_FORBIDDEN: Application service has not registered this user]```

When I list the users of my matrix server it is striking that all the signal users seem to have a bad unicode instead of the `+` sign in the phone number... etc
```
@signal_=2b49176*******:myserver.org
```
I am wondering if this is the reason for the error.

This is my `signal-registration.yaml`
```
id: ****
hs_token: **
as_token: ****
namespaces:
  users:
    - exclusive: true
      regex: '@signal_.*'
  aliases:
    - exclusive: true
      regex: '#signal_.*'
  rooms: []
url: http://myserver.org:8091
sender_localpart: signalbot
rate_limited: true
protocols: null
```
